In [ ]:
#----------classification--KNN-----------#

In [1]:
import pandas as pd

In [3]:
data=pd.read_csv("student_knn_classification.csv")

In [5]:
data.head()

   Study_Hours  Attendance Result
0            2          55   Fail
1            3          60   Fail
2            4          65   Fail
3            5          70   Pass
4            6          75   Pass

In [27]:
from sklearn.neighbors import KNeighborsClassifier
x=data[["Study_Hours","Attendance"]]
y=data["Result"]
model=KNeighborsClassifier()
model.fit(x,y)
new_data=pd.DataFrame({
    "Study_Hours":[7],
    "Attendance" : [80]
})
res=model.predict(new_data)
print(res)

['Pass']

In [ ]:
#---------Regression  KNN-------------------------------------#

In [29]:
data1=pd.read_csv("student_knn_regression.csv")

In [31]:
data1.head()

   Study_Hours  Attendance  Marks
0            2          55     35
1            3          60     40
2            4          65     50
3            5          70     60
4            6          75     70

In [35]:
from sklearn.neighbors import KNeighborsRegressor
x=data1[["Study_Hours","Attendance"]]
y=data1["Marks"]
model=KNeighborsRegressor()
model.fit(x,y)
new_model=pd.DataFrame({
    "Study_Hours":[1],
    "Attendance":[90]
})
res=model.predict(new_data)
print(res)

[76.]