In [ ]:
#--------------------------------logistic regression------------------#

In [ ]:
#--Binary LR---#

In [1]:
import pandas as pd
from sklearn.linear_model import LogisticRegression

In [4]:
data = pd.read_csv("logistic_binary.csv")

In [8]:
data.head()

   Study_Hours  Result
0            1       0
1            2       0
2            3       0
3            4       0
4            5       1

In [10]:
X = data[['Study_Hours']]
y = data['Result']
model = LogisticRegression()
model.fit(X, y)
new_data = pd.DataFrame({'Study_Hours': [5]})
prediction = model.predict(new_data)
print("Prediction:", prediction)

Prediction: [1]

In [ ]:
#-------multinomial regression-------------------#

In [62]:
datas = {
    "Study_Hours": [1,2,3,4,5,6,7,8,9,10],
    "Attendance": [50,55,60,65,70,75,80,85,90,95],
    "Preferred_Subject": [
        "Math","Science","English",
        "Math","Science","English",
        "Math","Science","English","Math"
    ]
}
print(datas)

   Study_Hours  Attendance Preferred_Subject
0            1          50              Math
1            2          55           Science
2            3          60           English
3            4          65              Math
4            5          70           Science
5            6          75           English
6            7          80              Math
7            8          85           Science
8            9          90           English
9           10          95              Math

In [66]:
df.head()

   Study_Hours  Attendance Preferred_Subject
0            1          50              Math
1            2          55           Science
2            3          60           English
3            4          65              Math
4            5          70           Science

In [68]:

X = df[["Study_Hours", "Attendance"]]
y = df["Preferred_Subject"]

model = LogisticRegression()
model.fit(X, y)
new_data = pd.DataFrame({
    "Study_Hours": [6],
    "Attendance": [78]
})
prediction = model.predict(new_data)
print("Predicted Subject:", prediction)

Predicted Subject: ['Math']

In [ ]:
#--------------ordinal regression-----------------#

In [46]:
data1 = pd.DataFrame({
    'Study_Hours':[1,2,3,4,5,6,7,8,9,10],
    'Attendance':[50,55,60,65,70,75,80,85,90,95],
    'Grade':['Low','Low','Low','Medium','Medium','Medium','High','High','High','High']
})

print(data1)

   Study_Hours  Attendance   Grade
0            1          50     Low
1            2          55     Low
2            3          60     Low
3            4          65  Medium
4            5          70  Medium
5            6          75  Medium
6            7          80    High
7            8          85    High
8            9          90    High
9           10          95    High

In [48]:
data1.head()

   Study_Hours  Attendance   Grade
0            1          50     Low
1            2          55     Low
2            3          60     Low
3            4          65  Medium
4            5          70  Medium

In [50]:
data1.tail()

   Study_Hours  Attendance   Grade
5            6          75  Medium
6            7          80    High
7            8          85    High
8            9          90    High
9           10          95    High

In [56]:

X = data[['Study_Hours', 'Attendance']]

y = data['Grade']
model = LogisticRegression()
model.fit(X, y)

new_data = pd.DataFrame({
    'Study_Hours': [1],
    'Attendance': [35]
})


prediction = model.predict(new_data)

print("\nPredicted Grade:", prediction[0])

Predicted Grade: Low