In [ ]:
#----------Random Forest--------classification--------------#

In [1]:
import pandas as pd
from sklearn.ensemble import RandomForestClassifier

In [3]:
data=pd.read_csv("student_knn_classification.csv")

In [5]:
data.head()

   Study_Hours  Attendance Result
0            2          55   Fail
1            3          60   Fail
2            4          65   Fail
3            5          70   Pass
4            6          75   Pass

In [9]:
x=data[["Study_Hours","Attendance"]]
y=data["Result"]
model=RandomForestClassifier(n_estimators=4)
model.fit(x,y)
new_data=pd.DataFrame({
    "Study_Hours":[1],
    "Attendance":[35]
})
res=model.predict(new_data)
print(res)

['Fail']

In [ ]:
#--------Regression---------------------#

In [19]:
from sklearn.ensemble import RandomForestRegressor

In [21]:
data1=pd.read_csv("student_knn_regression.csv")

In [23]:
data1.head()

   Study_Hours  Attendance  Marks
0            2          55     35
1            3          60     40
2            4          65     50
3            5          70     60
4            6          75     70

In [25]:
x=data1[["Study_Hours","Attendance"]]
y=data1["Marks"]
model = RandomForestRegressor(n_estimators=4)
model.fit(x,y)
new_data=pd.DataFrame({
    "Study_Hours":[1],
    "Attendance":[35]
})
res=model.predict(new_data)
print(res)

[35.]